"""
ABC constants: chord limits, timing, MIDI controller values.
From AbcConstants.java.
"""

from __future__ import annotations

# Chord
MAX_CHORD_NOTES = 6

# Timing
ONE_SECOND_MICROS = 1_000_000
ONE_MINUTE_MICROS = 60 * ONE_SECOND_MICROS
SHORTEST_NOTE_MICROS = ONE_MINUTE_MICROS // 1000
LONGEST_NOTE_MICROS = 8 * ONE_SECOND_MICROS
LONGEST_COUNT_IN_MICROS = ONE_SECOND_MICROS * 12
SHORTEST_NOTE_SECONDS = 0.06
SHORTEST_NOTE_SECONDS_FLOAT = 0.06
LONGEST_NOTE_SECONDS = 8.0
LONGEST_NOTE_MICROS_WORST_CASE = (2 * SHORTEST_NOTE_MICROS - 1) * (
    LONGEST_NOTE_MICROS // (2 * SHORTEST_NOTE_MICROS - 1)
)
MAX_TEMPO = int(ONE_MINUTE_MICROS / SHORTEST_NOTE_MICROS)
MIN_TEMPO = int((ONE_MINUTE_MICROS + LONGEST_NOTE_MICROS // 2) / LONGEST_NOTE_MICROS)

# Note length modifications for LOTRO instrument sound
NON_SUSTAINED_NOTE_HOLD_SECONDS = 1.5
SUSTAINED_NOTE_HOLD_SECONDS = 0.0
NOTE_RELEASE_SECONDS = 0.2
STUDENT_FX_MIN_SECONDS = 1.5

# MIDI Preview controller values
MIDI_REVERB = 0
MIDI_CHORUS = 0

# Note ID for Cowbells in ABC
COWBELL_NOTE_ID = 71

# B2 = 35, Fs2 = 30 (MIDI)
BAGPIPE_LAST_DRONE_NOTE_ID = 35
STUDENT_FIDDLE_LAST_FLUB_NOTE_ID = 30

# PPQN base: lots of prime factors for divisibility (from AbcToMidi)
DEFAULT_NOTE_TICKS = (2**6) * (3**2) * 5
