"""
MIDI constants: meta types, controller numbers, channel counts.
From MidiConstants.java.
"""

# Meta message types
META_TEXT = 0x01
META_COPYRIGHT = 0x02
META_TRACK_NAME = 0x03
META_INSTRUMENT_NAME = 0x04
META_LYRIC = 0x05
META_MARKER = 0x06
META_CUE_POINT = 0x07
META_PROGRAM_NAME = 0x08
META_PORT_NAME = 0x09
META_END_OF_TRACK = 0x2F
META_M_LIVE = 0x4B
META_TEMPO = 0x51
META_SMPTE_OFFSET = 0x54
META_TIME_SIGNATURE = 0x58
META_KEY_SIGNATURE = 0x59
META_PORT_CHANGE = 0x21

# Controllers
CHANNEL_VOLUME_CONTROLLER_COARSE = 0x07
CHANNEL_VOLUME_CONTROLLER_FINE = 0x27
CHANNEL_EXPRESSION_CONTROLLER = 0x0B
RESET_ALL_CONTROLLERS = 0x79
ALL_NOTES_OFF = 0x7B
SUSTAIN_OFF = 0x40
REGISTERED_PARAMETER_NUMBER_MSB = 0x65
REGISTERED_PARAMETER_NUMBER_LSB = 0x64
DATA_ENTRY_COARSE = 0x06
DATA_ENTRY_FINE = 0x26
DATA_BUTTON_INCREMENT = 0x60
DATA_BUTTON_DECREMENT = 0x61
BANK_SELECT_MSB = 0x00
BANK_SELECT_LSB = 0x20

DRUM_CHANNEL = 9
CHANNEL_COUNT = 16
CHANNEL_COUNT_ABC = 25
PORT_COUNT = 128
LOWEST_NOTE_ID = 0
HIGHEST_NOTE_ID = 127
NOTE_COUNT = HIGHEST_NOTE_ID - LOWEST_NOTE_ID + 1
MAX_VOLUME = 127
MAX_EXPRESSION = 127
PAN_CENTER = 64

PAN_CONTROL = 0x0A
REVERB_CONTROL = 0x5B
TREMOLO_CONTROL = 0x5C
CHORUS_CONTROL = 0x5D
DETUNE_CONTROL = 0x5E
PHASER_CONTROL = 0x5F

DEFAULT_TEMPO_BPM = 120
DEFAULT_TEMPO_MPQ = 500000
DEFAULT_INSTRUMENT = 0
DEFAULT_CHANNEL_VOLUME = 100
DEFAULT_EXPRESSION = 127
